# Site settings
baseurl: ""
url: "https://2023.d2r2.aksw.org"
rootResource: "<https://2023.d2r2.aksw.org/>"
development: false
language: en
otherlanguage: de
correspondingEditor: Natanael Arndt

# Build settings
timezone: Europe/Berlin
markdown: kramdown
kramdown:
  parse_block_html: true

plugins:
  - jekyll-rdf
exclude:
  - Gemfile
  - Gemfile.lock
jekyll_rdf:
  restriction: "SELECT ?resourceUri WHERE { ?resourceUri ?p ?o . FILTER regex(str(?resourceUri), \"^https://2023.d2r2.aksw.org/\") }"
  path: "graph.ttl"
