version: '3'

vars:
  JEKYLL_IMAGE: ghcr.io/aksw/jekyll-rdf:4.0.4
  WORKING_DIRECTORY: '{{.PWD}}'
  TARGET: _site
  BUILD_WATCH_FILES: find . -name '*' -not -path "./.git/*" -not -path "./.git" -not -path "./.jekyll-cache/*" -not -path "./.jekyll-cache"

tasks:
  sources:get-vol-xxx:
    - |
      echo \
      https://ceur-ws.org/Vol-XXX/index.html \
      https://ceur-ws.org/ceur-ws.css \
      https://ceur-ws.org/ceurws-bg.png \
      https://ceur-ws.org/CEUR-WS-logo.png \
      https://ceur-ws.org/cc-by_100x35.png \
      https://ceur-ws.org/ceurws-bullet-6x12.png \
      https://ceur-ws.org/favicon.ico \
      https://ceur-ws.org/CEUR-WS-logo-blue.png \
      | xargs -n 1 curl -O
    - mv index.html Vol-XXX/index.html

  build:
    desc: Build the site locally
    cmds:
      - |
        docker run --rm \
        --workdir /workspace \
        -v {{.WORKING_DIRECTORY}}:/workspace \
        -e TZ=Europe/Berlin {{.JEKYLL_USER_ARG}} -e BUNDLE_PATH=.vendor \
        {{.JEKYLL_IMAGE}} jekyll build -d {{.TARGET}}

  serve:
    desc: Serve the locally built site
    cmds:
      - python -m http.server --directory {{.TARGET}}

  watch:
    desc: Serve the page and rebuild it on changes
    deps:
      - task: serve
      - task: build:watch
    cmds:
      - echo "Terminate"

  build:watch:
    desc: Watch for changes in the directory and rebuild the page, should be combined with task serve in a second terminal
    cmds:
      - '{{.BUILD_WATCH_FILES}} | entr task build'

  check:graph-serialization:
    desc: Verify the graphs syntax is correct
    cmds:
      - rapper -c -i turtle graph.ttl

  graph:get-program:
    desc: Get the program from cmem
    cmds:
      - cmemc -c aksw.eccenca.dev graph export https://dataweek.de/d2r2-22/ | rapper -i turtle -o turtle - https://dataweek.de/d2r2-22/ > paper.ttl
